azure_subscription_id = "a4fc6db1-7213-40d1-891d-ebfde61dcf79"
api_jwtpassword = "passwordjwt"
api_db_user = "postgres"
api_db_password = "prueba-tenpo"
api_db_host = "myterraformpublicipdbtenpo.eastus.cloudapp.azure.com"
api_db_database = "tenpo-bd"
api_db_port = "5432"
